server:
  port: 8089

spring:
  application:
    name: tarotalk-scheduler-service

integrations:
  orchestrator:
    base-url: http://localhost:8077

scheduler:
  loop-delay-ms: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%property{spring.application.name}] [%X{traceId}] [%X{userId}] %logger{36} - %msg%n"
