server:
  port: 8089

spring:
  application:
    name: tarotalk-scheduler-service

integrations:
  ai-service:
    base-url: http://localhost:8090
  chat-service:
    base-url: http://localhost:8084
  feed-service:
    base-url: http://localhost:8085

scheduler:
  loop-delay-ms: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info
