server:
  port: 8086

spring:
  application:
    name: tarotalk-presence-service
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%property{spring.application.name}] [%X{traceId}] [%X{userId}] %logger{36} - %msg%n"
