server:
  port: 8088

spring:
  application:
    name: tarotalk-relationship-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

management:
  endpoints:
    web:
      exposure:
        include: health,info
